# Generated by Django 4.2.7 on 2024-04-08 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_alter_product_info_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_info',
            name='delevary_charge',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=10, null=True),
        ),
    ]
