# Generated by Django 4.2.7 on 2024-04-08 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_product_info_delevary_charge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_info',
            name='delevary_charge',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
    ]
