# Generated by Django 4.2.7 on 2024-04-10 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchased_product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchased_product',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to='invoices/'),
        ),
    ]
