# Generated by Django 4.2.7 on 2024-04-10 04:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('purchased_product', '0002_purchased_product_pdf_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchased_product',
            name='pdf_file',
        ),
        migrations.CreateModel(
            name='invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='invoices/')),
                ('purchased_product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='purchased_product.purchased_product')),
            ],
        ),
    ]
