# Generated by Django 4.2.7 on 2024-04-08 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_cart_delevary_charge_cart_discount_cart_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='total',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
