# Generated by Django 4.2.7 on 2024-04-08 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0004_alter_cart_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='discount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='input the percentage', max_digits=5, max_length=5, null=True),
        ),
    ]
