# Generated by Django 4.2.7 on 2024-04-09 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deposite', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='deposit',
            name='date_time_field',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
